spring.application.name: todo-service
spring:
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
    flyway:
      enabled: true
debug: false



